### ISSUE TITLE
como Programador, necesito conocer el diagrama de componentes

### ISSUE THREAD

**Issue by camilosuarezserpiente** [camilosuarezserpiente/GAES5#3]

**Comment by Mh238** [comment]
[Diagrama de componentes SecurityConnect.pdf]

**Comment by Mh238** [comment]
[Diagrama de componentes SecurityConnect.pdf](https://github.com/user-attachments/files/18029997/Diagrama.de.componentes.SecurityConnect.pdf)
![DIAGRAMA DE COMPONENTES](https://github.com/user-attachments/assets/2afdf9bb-c7c5-46d5-94d4-f5f27a113979)
